### PR TITLE
Symfony 3.3.10 changing the way how the mapping is readed urlFrom -> url_from

### PR DESCRIPTION
**Pull request by cf-jlambelet**
Got an error during the usage of
`php bin/console doctrine:schema:update --force` 
the column url_form doesn't exists.

Version of symfony 3.3.10

### CODE REVIEW

**Comment by pkraeutli** [comment]
The column name probably depends on the the doctrine configuration. Are you using `UnderscoreNamingStrategy` or something?

**Comment by cf-jlambelet** [comment]
Actually, I didn't change this actively. When creating the project, I am using the symfony installer, and by default, indeed the configuration indicate:
`orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true`

So I guess my quickfix, isn't the proper one.

**Comment by cf-jlambelet** [comment]
But in the file Map.orm.yml, on the line 23, it is written urlForm

**Comment by cf-jlambelet** [comment]
Would be the solution to add in the configuration in Map.orm.yml on line 24 under urlForm the setting : `column: urlForm`
 to avoid conflict with the naming strategy?

https://github.com/origammi/AstinaRedirectManagerBundle/blob/master/Resources/config/doctrine/Map.orm.yml#L23

**Comment by pkraeutli** [comment]
It's possible, you'll have to try.
Another option (or workaround) is to override the mapping file in your application.
Putting it at `app/Resources/AstinaRedirectManagerBundle/config/doctrine/Map.orm.yml` should do the trick.

**Comment by cf-jlambelet** [comment]
using the option `column` make your bundle working again with the default name_strategy `UnderscoreNamingStrategy` :)
I do not exactly how you prefer your PR, but if you want to merge, the code is updated.

**Pull request closed without merging**
